// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Used by push setup; false only when options are still placeholders.
  static bool get isConfigured {
    final key = android.apiKey;
    return key.isNotEmpty && !key.startsWith('REPLACE_');
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1xz00F7xW21OPuA8-7DSWualirZqWNA0',
    appId: '1:313747954087:web:c3a2d5d4064a82e9b13e82',
    messagingSenderId: '313747954087',
    projectId: 'mood-studios-3172f',
    authDomain: 'mood-studios-3172f.firebaseapp.com',
    storageBucket: 'mood-studios-3172f.firebasestorage.app',
    measurementId: 'G-996P2E2PJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJHuguGGtMtJHd2TqyWIoIUHcQZSRML8M',
    appId: '1:313747954087:android:54b4469e87ef23abb13e82',
    messagingSenderId: '313747954087',
    projectId: 'mood-studios-3172f',
    storageBucket: 'mood-studios-3172f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfkIDz7tdW3YL5F07f_2_zYD-un6Zl5UQ',
    appId: '1:313747954087:ios:671453c0f008e094b13e82',
    messagingSenderId: '313747954087',
    projectId: 'mood-studios-3172f',
    storageBucket: 'mood-studios-3172f.firebasestorage.app',
    iosBundleId: 'com.moodstudios.moodStudiosMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfkIDz7tdW3YL5F07f_2_zYD-un6Zl5UQ',
    appId: '1:313747954087:ios:671453c0f008e094b13e82',
    messagingSenderId: '313747954087',
    projectId: 'mood-studios-3172f',
    storageBucket: 'mood-studios-3172f.firebasestorage.app',
    iosBundleId: 'com.moodstudios.moodStudiosMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1xz00F7xW21OPuA8-7DSWualirZqWNA0',
    appId: '1:313747954087:web:4fc1929ca2023dbab13e82',
    messagingSenderId: '313747954087',
    projectId: 'mood-studios-3172f',
    authDomain: 'mood-studios-3172f.firebaseapp.com',
    storageBucket: 'mood-studios-3172f.firebasestorage.app',
    measurementId: 'G-YWDDDHVEMQ',
  );
}
